### ISSUE TITLE
Updates for TextDiffuser-2

### ISSUE THREAD

**Issue by JingyeChen** [yeungchenwa/Recommendations-Diffusion-Text-Image#18]
Hi, thanks for maintaining this awesome recommendation repo! Here are some updated links for TextDiffuser-2:

Demo: https://huggingface.co/spaces/JingyeChen22/TextDiffuser-2
Homepage: https://jingyechen.github.io/textdiffuser2/

May you update the readme file at your convenience? Thanks!

**Comment by yeungchenwa** [comment]
Hi, jingye! Thanks for your contribution! We have updated the links!
